// <auto-generated />
namespace ChiquePiggyFidelimax.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class atualization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atualization));
        
        string IMigrationMetadata.Id
        {
            get { return "202212072159512_atualization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
